version: "3"
services:
  api-gateway-blue:
    build:
      context: ./back/gateway
      dockerfile: Dockerfile
    container_name: api-gateway-blue
    ports:
      - "8765:8765"
    networks:
      - maonnet
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

networks:
  maonnet:
    external: true